/* miraculous.kk — global data bridge */
(() => {
  "use strict";
  const SUPABASE_URL = "https://gfnpyzmhhwkpzvjwkckg.supabase.co";
  const SUPABASE_KEY = "sb_publishable_CGhjWdOcexqk0ac_WyYfOg_3jif0Bwz";
  const table = "global_announcements";
  let client = null;
  function log(...a){ try{ console.log("[GlobalDB]", ...a); }catch(_){} }
  function esc(v=""){ return String(v).replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m])); }
  function makeId(){ return (crypto?.randomUUID?.() || Date.now().toString(36)+Math.random().toString(36).slice(2)); }
  function normalize(row){ return {id:String(row.id),label:row.label||"NOVIDADE",title:row.title||"",text:row.body||row.text||"",color:row.color||"#e62b45",createdAt:row.created_at?new Date(row.created_at).getTime():(row.createdAt||Date.now()),expiresAt:row.expires_at?new Date(row.expires_at).getTime():(row.expiresAt||0)}; }
  async function getClient(){ if(client)return client; if(window.supabaseClient){client=window.supabaseClient;return client;} const mod=await import("https://esm.sh/@supabase/supabase-js@2"); client=mod.createClient(SUPABASE_URL,SUPABASE_KEY); window.supabaseClient=client; return client; }
  async function read(){ const sb=await getClient(); const {data,error}=await sb.from(table).select("*").order("created_at",{ascending:false}); if(error)throw error; return (data||[]).map(normalize).filter(x=>!x.expiresAt||x.expiresAt>Date.now()); }
  function paint(rows){ window.announcements=rows; if(typeof window.renderAnnouncements==="function")window.renderAnnouncements(); const c=document.getElementById("announcementCount"); if(c)c.textContent=String(rows.length); }
  async function refresh(){ try{paint(await read());log("anúncios globais sincronizados");return true;}catch(e){log("sync falhou",e);return false;} }
  async function publish({label,title,text,color,expiresAt=0}){ const sb=await getClient(); const row={id:makeId(),label:label||"NOVIDADE",title,text:text||"",color:color||"#e62b45",created_at:new Date().toISOString(),expires_at:expiresAt?new Date(expiresAt).toISOString():null}; const {error}=await sb.from(table).insert(row); if(error)throw error; await refresh(); return row; }
  async function migrateLocal(){ try{ if(typeof getAll!=="function")return; const local=await getAll("announcements"); if(!local?.length)return; const sb=await getClient(); const {data:existing,error}=await sb.from(table).select("id"); if(error)throw error; const ids=new Set((existing||[]).map(x=>String(x.id))); const rows=local.filter(a=>a?.id&&!ids.has(String(a.id))).map(a=>({id:String(a.id),label:a.label||"NOVIDADE",title:a.title||"",body:a.text||"",color:a.color||"#e62b45",created_at:new Date(a.createdAt||Date.now()).toISOString(),expires_at:a.expiresAt?new Date(a.expiresAt).toISOString():null})); if(rows.length){const {error:e}=await sb.from(table).insert(rows);if(e)throw e;log("migrados",rows.length,"anúncios locais");}}catch(e){log("migração local falhou",e);} }
  function installAdminPublisher(){ const btn=document.getElementById("addAnnouncement"); if(!btn||btn.dataset.globalDbInstalled)return; btn.dataset.globalDbInstalled="1"; btn.onclick=async()=>{ const status=document.getElementById("announcementStatus"); if(!window.currentUser?.admin){if(status)status.innerHTML='<div class="notice error">❌ Apenas administradores podem publicar anúncios.</div>';return;} const title=document.getElementById("announcementTitle")?.value.trim(); const text=document.getElementById("announcementText")?.value.trim(); const label=document.getElementById("announcementLabel")?.value.trim()||"NOVIDADE"; const color=document.getElementById("announcementColor")?.value||"#e62b45"; const duration=Number(document.getElementById("announcementDuration")?.value||0); if(!title||!text){if(status)status.innerHTML='<div class="notice error">❌ Preenche o título e o texto.</div>';return;} try{if(status)status.innerHTML='<div class="notice">☁️ A publicar globalmente…</div>';await publish({label,title,text,color,expiresAt:duration>0?Date.now()+duration:0});document.getElementById("announcementTitle").value="";document.getElementById("announcementText").value="";if(status)status.innerHTML='<div class="notice success">✅ Anúncio publicado para todos os dispositivos!</div>';}catch(e){console.error("[GlobalDB] publicação falhou",e);if(status)status.innerHTML=`<div class="notice error">❌ Falha ao publicar globalmente: ${esc(e?.message||"erro")}</div>`;}}; }
  async function realtime(){ try{const sb=await getClient();sb.channel("global-announcements-live").on("postgres_changes",{event:"*",schema:"public",table},()=>refresh()).subscribe();log("Realtime ligado");}catch(e){log("Realtime indisponível",e);} }
  async function boot(){ await migrateLocal(); await refresh(); installAdminPublisher(); await realtime(); setInterval(()=>{installAdminPublisher();refresh().catch(()=>{});},30000); window.miraculousGlobalDB={refresh,publish,migrateLocal}; }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
