(() => {
  'use strict';
  const sb = window.supabaseClient || window.miraculousSupabase;
  if (!sb) { console.error('[V5] Supabase client unavailable'); return; }
  const $ = id => document.getElementById(id);
  const esc = (v='') => String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const toast = (msg,ok=true) => window.mkkToast ? window.mkkToast(ok?'Miraculous.kk':'Erro',msg,ok?'success':'error') : alert(msg);
  function remoteToLocal(r){return {id:String(r.id),series:r.series||'Miraculous',title:r.title||'Episódio',season:r.season||'—',number:r.episode_number||'—',lang:r.language||'PT-PT',desc:r.description||'',imdbUrl:r.imdb_url||'',trailerUrl:r.trailer_url||'',videoUrl:r.video_url||'',videoStorage:r.video_url?{kind:'vercel-blob',url:r.video_url}:null,videoKind:r.video_url?'mp4':'',videoType:'video/mp4',videoSize:0,subtitlesUrl:r.subtitles_url||'',subtitles:{},thumbnail:r.thumbnail_url||'',published:r.published!==false,updatedAt:Date.parse(r.updated_at||r.created_at||'')||Date.now()};}
  async function pull(){const {data,error}=await sb.from('episodes').select('*').eq('published',true).order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){console.warn('[V5] episodes:',error.message);return}if(typeof window.getAll!=='function'||typeof window.put!=='function')return;const rows=(data||[]).map(remoteToLocal),ids=new Set(rows.map(x=>x.id));for(const x of await window.getAll('episodes'))if(!ids.has(String(x.id)))await window.remove('episodes',x.id);for(const x of rows)await window.put('episodes',x);await window.loadData?.();}
  async function admin(){const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Inicia sessão primeiro.');await sb.rpc('bootstrap_first_admin').catch(()=>{});const {data,error}=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(error)throw error;if(!data)throw new Error('Esta conta não é administradora.');return user;}
  async function publish(){const add=$('add');if(!add||add.dataset.v5Bound)return;add.dataset.v5Bound='1';add.addEventListener('click',async ev=>{ev.preventDefault();ev.stopImmediatePropagation();try{await admin();const title=$('title')?.value.trim();if(!title)throw new Error('Escreve um título.');const id=window.__mkkV5EditingId||crypto.randomUUID();const old=(await window.getAll('episodes')).find(x=>String(x.id)===String(id));let videoUrl=$('videoUrl')?.value.trim()||old?.videoUrl||'';const file=$('videoFile')?.files?.[0];if(file){if(!/\.mp4$/i.test(file.name)&&!String(file.type).startsWith('video/'))throw new Error('Seleciona um MP4 válido.');$('status').innerHTML='<div class="notice">☁️ A enviar o MP4… <b id="v5VideoProgress">0%</b></div>';if(typeof window.uploadVideoToVercelBlob!=='function')throw new Error('Upload de MP4 indisponível.');const result=await window.uploadVideoToVercelBlob(file,id,p=>{const x=$('v5VideoProgress');if(x)x.textContent=p+'%'});if(!result?.url)throw new Error('O upload não devolveu um URL público.');videoUrl=result.url}let thumbnail=old?.thumbnail||'';const tf=$('thumb')?.files?.[0];if(tf)thumbnail=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>rej(r.error);r.readAsDataURL(tf)});let subtitlesUrl=old?.subtitlesUrl||'';const sf=$('subtitleFile')?.files?.[0];if(sf){const txt=await sf.text();const vtt=txt.trimStart().startsWith('WEBVTT')?txt:'WEBVTT\n\n'+txt.replace(/\r/g,'').replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g,'$1.$2');subtitlesUrl='data:text/vtt;charset=utf-8,'+encodeURIComponent(vtt)}const row={id,title,series:$('series')?.value||'Miraculous',season:$('season')?.value.trim()||'—',episode_number:$('number')?.value.trim()||'—',language:$('lang')?.value.trim()||'PT-PT',thumbnail_url:thumbnail,video_url:videoUrl,description:$('desc')?.value.trim()||'',imdb_url:$('imdbUrl')?.value.trim()||'',trailer_url:$('trailerUrl')?.value.trim()||'',subtitles_url:subtitlesUrl,published:true,sort_order:Number($('number')?.value||0),updated_at:new Date().toISOString()};$('status').innerHTML='<div class="notice">🌍 A publicar na database global…</div>';const {data,error}=await sb.from('episodes').upsert(row,{onConflict:'id'}).select().single();if(error)throw error;await window.put('episodes',remoteToLocal(data));window.__mkkV5EditingId=null;window.resetForm?.();await window.loadData?.();$('status').innerHTML='<div class="notice success">✅ Episódio publicado globalmente. Já aparece para todos os browsers.</div>';toast('Episódio publicado para toda a gente.')}catch(e){console.error('[V5] publish',e);$('status').innerHTML=`<div class="notice error">❌ ${esc(e.message||'Não foi possível publicar o episódio.')}</div>`}},true)}
  function deleteHook(){const fn=window.deleteEpisode;if(typeof fn!=='function'||fn.__v5)return;const wrapped=async id=>{try{await admin();const {error}=await sb.from('episodes').delete().eq('id',id);if(error)throw error;await window.remove?.('episodes',id);await pull();toast('Episódio apagado.')}catch(e){alert('Não foi possível apagar: '+(e.message||e))}};wrapped.__v5=true;window.deleteEpisode=wrapped;}
  async function start(){await pull();await publish();deleteHook();sb.channel('miraculous-v5-episodes').on('postgres_changes',{event:'*',schema:'public',table:'episodes'},()=>pull().catch(()=>{})).subscribe();console.log('[V5] global episodes + realtime + MP4 upload ready');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
